//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hisba.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hisba.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Command_Add {
            get {
                return ResourceManager.GetString("Command_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Command_Cancel {
            get {
                return ResourceManager.GetString("Command_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Command_Copy {
            get {
                return ResourceManager.GetString("Command_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Command_Edit {
            get {
                return ResourceManager.GetString("Command_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields.
        /// </summary>
        public static string Command_EmptyFields {
            get {
                return ResourceManager.GetString("Command_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export excel.
        /// </summary>
        public static string Command_ExportExcel {
            get {
                return ResourceManager.GetString("Command_ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Command_Favorite {
            get {
                return ResourceManager.GetString("Command_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed columns.
        /// </summary>
        public static string Command_GridColumnsChooser {
            get {
                return ResourceManager.GetString("Command_GridColumnsChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Filters.
        /// </summary>
        public static string Command_GridDeleteFilters {
            get {
                return ResourceManager.GetString("Command_GridDeleteFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Command_GridFilter {
            get {
                return ResourceManager.GetString("Command_GridFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter editor.
        /// </summary>
        public static string Command_GridFilterEditor {
            get {
                return ResourceManager.GetString("Command_GridFilterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table appearance.
        /// </summary>
        public static string Command_GridLayout {
            get {
                return ResourceManager.GetString("Command_GridLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the appearance.
        /// </summary>
        public static string Command_GridResetLayout {
            get {
                return ResourceManager.GetString("Command_GridResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved filters.
        /// </summary>
        public static string Command_GridSavedFilters {
            get {
                return ResourceManager.GetString("Command_GridSavedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the filter.
        /// </summary>
        public static string Command_GridSaveFilter {
            get {
                return ResourceManager.GetString("Command_GridSaveFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the appearance.
        /// </summary>
        public static string Command_GridSaveLayout {
            get {
                return ResourceManager.GetString("Command_GridSaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Command_New {
            get {
                return ResourceManager.GetString("Command_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Command_Refresh {
            get {
                return ResourceManager.GetString("Command_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        public static string Command_SaveAndClose {
            get {
                return ResourceManager.GetString("Command_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; New.
        /// </summary>
        public static string Command_SaveAndNew {
            get {
                return ResourceManager.GetString("Command_SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Command_Validate {
            get {
                return ResourceManager.GetString("Command_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count={0}.
        /// </summary>
        public static string GridControl_ItemsCount {
            get {
                return ResourceManager.GetString("GridControl_ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected={0}.
        /// </summary>
        public static string GridControl_SelectedItemsCount {
            get {
                return ResourceManager.GetString("GridControl_SelectedItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Property_AddGoodsReceipt {
            get {
                return ResourceManager.GetString("Property_AddGoodsReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Property_Address {
            get {
                return ResourceManager.GetString("Property_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount (DA).
        /// </summary>
        public static string Property_Amount {
            get {
                return ResourceManager.GetString("Property_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount HT.
        /// </summary>
        public static string Property_AmountHT {
            get {
                return ResourceManager.GetString("Property_AmountHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Property_Category {
            get {
                return ResourceManager.GetString("Property_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Property_Code {
            get {
                return ResourceManager.GetString("Property_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string Property_Created {
            get {
                return ResourceManager.GetString("Property_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Property_Creator {
            get {
                return ResourceManager.GetString("Property_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string Property_DateCreation {
            get {
                return ResourceManager.GetString("Property_DateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date.
        /// </summary>
        public static string Property_DateModification {
            get {
                return ResourceManager.GetString("Property_DateModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Property_DateOfBirth {
            get {
                return ResourceManager.GetString("Property_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Property_Description {
            get {
                return ResourceManager.GetString("Property_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Property_Discount {
            get {
                return ResourceManager.GetString("Property_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount%.
        /// </summary>
        public static string Property_DiscountPercentage {
            get {
                return ResourceManager.GetString("Property_DiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Property_Driver {
            get {
                return ResourceManager.GetString("Property_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Property_Email {
            get {
                return ResourceManager.GetString("Property_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Property_FirstName {
            get {
                return ResourceManager.GetString("Property_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string Property_FullName {
            get {
                return ResourceManager.GetString("Property_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gendor.
        /// </summary>
        public static string Property_Gendor {
            get {
                return ResourceManager.GetString("Property_Gendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Number.
        /// </summary>
        public static string Property_IdentificationNumber {
            get {
                return ResourceManager.GetString("Property_IdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Property_Label {
            get {
                return ResourceManager.GetString("Property_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Property_LastName {
            get {
                return ResourceManager.GetString("Property_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string Property_Margin {
            get {
                return ResourceManager.GetString("Property_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin%.
        /// </summary>
        public static string Property_MarginPercentage {
            get {
                return ResourceManager.GetString("Property_MarginPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date.
        /// </summary>
        public static string Property_Modified {
            get {
                return ResourceManager.GetString("Property_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Property_Modifier {
            get {
                return ResourceManager.GetString("Property_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net amount HT.
        /// </summary>
        public static string Property_NetAmountHT {
            get {
                return ResourceManager.GetString("Property_NetAmountHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net amount TTC.
        /// </summary>
        public static string Property_NetAmountTTC {
            get {
                return ResourceManager.GetString("Property_NetAmountTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Property_PhoneNumber {
            get {
                return ResourceManager.GetString("Property_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Price HT.
        /// </summary>
        public static string Property_PriceHT {
            get {
                return ResourceManager.GetString("Property_PriceHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Price TTC.
        /// </summary>
        public static string Property_PriceTTC {
            get {
                return ResourceManager.GetString("Property_PriceTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Price (DA).
        /// </summary>
        public static string Property_ProductPrice {
            get {
                return ResourceManager.GetString("Property_ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase price.
        /// </summary>
        public static string Property_PurchasePrice {
            get {
                return ResourceManager.GetString("Property_PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase price HT.
        /// </summary>
        public static string Property_PurchasePriceHT {
            get {
                return ResourceManager.GetString("Property_PurchasePriceHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Property_Quantity {
            get {
                return ResourceManager.GetString("Property_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity in stock.
        /// </summary>
        public static string Property_QuantityInStock {
            get {
                return ResourceManager.GetString("Property_QuantityInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref.
        /// </summary>
        public static string Property_Reference {
            get {
                return ResourceManager.GetString("Property_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price.
        /// </summary>
        public static string Property_SalePrice {
            get {
                return ResourceManager.GetString("Property_SalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price HT.
        /// </summary>
        public static string Property_SalePriceHT {
            get {
                return ResourceManager.GetString("Property_SalePriceHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price TTC.
        /// </summary>
        public static string Property_SalePriceTTC {
            get {
                return ResourceManager.GetString("Property_SalePriceTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string Property_Status {
            get {
                return ResourceManager.GetString("Property_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total HT.
        /// </summary>
        public static string Property_TotalHT {
            get {
                return ResourceManager.GetString("Property_TotalHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total TTC.
        /// </summary>
        public static string Property_TotalTTC {
            get {
                return ResourceManager.GetString("Property_TotalTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total TVA.
        /// </summary>
        public static string Property_TotalTVA {
            get {
                return ResourceManager.GetString("Property_TotalTVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVA.
        /// </summary>
        public static string Property_TVA {
            get {
                return ResourceManager.GetString("Property_TVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVA%.
        /// </summary>
        public static string Property_TVAPercentage {
            get {
                return ResourceManager.GetString("Property_TVAPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Property_Username {
            get {
                return ResourceManager.GetString("Property_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Title_Add {
            get {
                return ResourceManager.GetString("Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string Title_AddProduct {
            get {
                return ResourceManager.GetString("Title_AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Title_Edit {
            get {
                return ResourceManager.GetString("Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string Title_EditProduct {
            get {
                return ResourceManager.GetString("Title_EditProduct", resourceCulture);
            }
        }
    }
}
